"""Tests for src/tinyrag/ingestion/parsers.py — document parsers.

Test layout
-----------
- TestPublicSurface     — every public name is exported from the
  subpackage (``tinyrag.ingestion.parse``, ``ParsedDocument``,
  ``ParserError``, ``DocumentParser``, the three concrete parsers).
- TestProtocolIsRuntime — :class:`DocumentParser` is
  ``@runtime_checkable``; all three concrete parsers satisfy it
  via duck-typing.
- TestParsedDocument    — the result dataclass is frozen; the
  ``pages`` default is empty (not mutable shared state).
- TestExtensionDispatch — :func:`parse` routes by extension
  (case-insensitive); raises :class:`UnsupportedFormatError` on
  unknown extensions.
- TestTxtParser         — happy path, missing file, empty file,
  whitespace-only file, UTF-8 BOM tolerance, exact contract.
- TestMarkdownParser    — happy path, front-matter stripped,
  image/link URL noise stripped, missing/empty files.
- TestPdfParser         — happy path (multi-page, page numbers
  preserved), missing file, empty PDF, malformed PDF.
- TestErrorHierarchy    — every public exception subclasses
  :class:`ParserError`; the right subclass is raised in each
  failure mode.

Why so many tests?
------------------
PDF parsing is famously finicky (the architecture doc calls this
out as 🟡 Standard review intensity). The failure modes — empty
files, encoded PDFs, scanned PDFs, missing front-matter, mixed
encoding — all need explicit coverage so a regression catches the
problem before the user does.

PDF fixture strategy
--------------------
No PDF writer library (``fpdf``, ``reportlab``, ``pypdf``) is in
our dependency tree. We construct minimal valid PDFs by hand using
PDF's text-based structure. A 2-page fixture is generated by
:func:`_build_minimal_pdf` — enough for ``pdfplumber`` to extract
text from each page.

Location: ``tests/test_parsers.py``
"""

from __future__ import annotations

import json
import zlib
from pathlib import Path

import pytest

from tinyrag.ingestion import (
    DocumentParser,
    EmptyDocumentError,
    MarkdownParser,
    ParsedDocument,
    ParserError,
    PdfParser,
    PdfReadError,
    TxtParser,
    UnsupportedFormatError,
    parse,
)

# ----------------------------------------------------------------------------
# Fixtures
# ----------------------------------------------------------------------------


@pytest.fixture
def fixtures_dir(tmp_path: Path) -> Path:
    """The directory all sample files live in for this test."""
    return tmp_path


@pytest.fixture
def sample_txt(fixtures_dir: Path) -> Path:
    """A normal TXT file with a few lines of body text."""
    p = fixtures_dir / "manual.txt"
    p.write_text(
        "Living-Room Thermostat Manual\n"
        "==============================\n"
        "\n"
        "1. Power on: hold the side button for 2 seconds.\n"
        "2. Pair with the app: Settings > Devices > Add.\n"
        "3. Set schedule: ...\n",
        encoding="utf-8",
    )
    return p


@pytest.fixture
def sample_txt_bom(fixtures_dir: Path) -> Path:
    """A TXT file with a UTF-8 BOM (Windows Notepad default)."""
    p = fixtures_dir / "bom.txt"
    p.write_text("\ufeffHello from Windows Notepad\n", encoding="utf-8")
    return p


@pytest.fixture
def empty_txt(fixtures_dir: Path) -> Path:
    p = fixtures_dir / "empty.txt"
    p.write_text("", encoding="utf-8")
    return p


@pytest.fixture
def whitespace_txt(fixtures_dir: Path) -> Path:
    p = fixtures_dir / "blank.txt"
    p.write_text("   \n\n\t\n", encoding="utf-8")
    return p


@pytest.fixture
def sample_md(fixtures_dir: Path) -> Path:
    """A Markdown file with front-matter, an image, and links."""
    p = fixtures_dir / "faq.md"
    p.write_text(
        "---\n"
        "title: Home FAQ\n"
        "author: TinyRAG\n"
        "---\n"
        "\n"
        "# FAQ\n"
        "\n"
        "## Pairing the bulb\n"
        "\n"
        "See the [official guide](https://example.com/guide) for details.\n"
        "The ![wiring diagram](https://example.com/diagram.png) shows the setup.\n"
        "\n"
        "## Resetting\n"
        "\n"
        "Hold the button for 10 seconds.\n",
        encoding="utf-8",
    )
    return p


@pytest.fixture
def md_no_frontmatter(fixtures_dir: Path) -> Path:
    """Markdown without front-matter — ``had_frontmatter`` should be False."""
    p = fixtures_dir / "plain.md"
    p.write_text("# Title\n\nSome plain [link](https://x.com) text.\n", encoding="utf-8")
    return p


@pytest.fixture
def md_only_frontmatter(fixtures_dir: Path) -> Path:
    """A Markdown file that is ONLY a front-matter block — should be EmptyDocumentError."""
    p = fixtures_dir / "fmonly.md"
    p.write_text("---\ntitle: nothing else\n---\n", encoding="utf-8")
    return p


# ----------------------------------------------------------------------------
# PDF fixture builder
# ----------------------------------------------------------------------------
#
# We construct a minimal valid PDF by hand. A PDF is a text-based
# container of objects; the minimum needed for pdfplumber to extract
# text is:
#
#   1. A catalog object (the PDF's root).
#   2. A pages object (the page tree root).
#   3. One or more page objects (each referencing a content stream
#      and a font resource).
#   4. A font object (we use the built-in Helvetica).
#   5. A content stream with the actual text-drawing operators.
#
# Each object is a numbered "X 0 obj ... endobj" block. The objects
# form a cross-reference table that pdfplumber walks to assemble the
# document. We rebuild the xref byte offsets dynamically after we
# know each object's final size.
#
# We use FlateDecode (zlib) compression on the content streams to
# keep the fixture small and to behave like a real-world PDF
# (most PDFs use FlateDecode for streams).


def _make_pdf_stream(text: str) -> bytes:
    """Build a single PDF content stream drawing ``text`` with Helvetica.

    The stream uses the ``Tj`` operator (show text). Newlines in
    the input become ``\\n`` in the rendered PDF (we don't draw
    actual line breaks; that's enough for our chunker).
    """
    # Escape PDF special characters in the text. PDF text strings
    # are wrapped in parentheses; we escape ``(`` and ``)`` and use
    # ``\\n`` for a literal newline.
    escaped = text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
    content = f"BT /F1 12 Tf 50 750 Td ({escaped}) Tj ET"
    return zlib.compress(content.encode("latin-1"))


def _build_minimal_pdf(pages: list[str]) -> bytes:
    """Build a minimal valid PDF with one page per entry in ``pages``.

    Each page's content stream draws the corresponding string. The
    PDF is intentionally tiny — no images, no fancy fonts — but
    pdfplumber can extract the text on each page correctly.
    """
    # Object 1: catalog. 2: pages. 3: font. Then page pairs (page + content).
    # Object numbering:
    #   1: Catalog
    #   2: Pages
    #   3: Font (F1, Helvetica)
    #   4..N: alternating Page / Content objects (4, 5, 6, 7, ...)
    n_pages = len(pages)
    objects: list[bytes] = [
        # 1: Catalog -> Pages
        b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
        # 2: Pages -> each Page
        b"2 0 obj\n<< /Type /Pages /Kids ["
        + b" ".join(f"{4 + 2 * i} 0 R".encode() for i in range(n_pages))
        + b"] /Count "
        + str(n_pages).encode()
        + b" >>\nendobj\n",
        # 3: Font
        b"3 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
    ]
    for i, page_text in enumerate(pages):
        page_obj_num = 4 + 2 * i
        content_obj_num = page_obj_num + 1
        stream_data = _make_pdf_stream(page_text)
        # Page object references its content stream and the font.
        objects.append(
            f"{page_obj_num} 0 obj\n"
            f"<< /Type /Page /Parent 2 0 R "
            f"/MediaBox [0 0 612 792] "
            f"/Contents {content_obj_num} 0 R "
            f"/Resources << /Font << /F1 3 0 R >> >> >>\n"
            f"endobj\n".encode()
        )
        # Content stream.
        objects.append(
            f"{content_obj_num} 0 obj\n"
            f"<< /Length {len(stream_data)} /Filter /FlateDecode >>\n"
            f"stream\n".encode()
            + stream_data
            + b"\nendstream\nendobj\n"
        )

    # Header.
    header = b"%PDF-1.4\n%\xc2\xa5\xc2\xb1\xc2\xab\n"  # binary marker
    body = b"".join(objects)

    # Cross-reference table. ``pdfplumber`` (via pypdf) needs this to
    # locate each object. We record the byte offset of every object
    # and emit the classic ASCII xref table (each entry is exactly
    # 20 bytes: 10-digit offset + space + 5-digit gen + space + flag).
    offsets: list[int] = []
    cur = len(header)
    for obj in objects:
        offsets.append(cur)
        cur += len(obj)
    xref_offset = len(header) + len(body)
    xref_block = (
        b"xref\n"
        + str(len(objects) + 1).encode()
        + b" 0\n"
        + b"0000000000 65535 f \n"
    )
    for off in offsets:
        xref_block += f"{off:010d} 00000 n \n".encode()
    trailer = (
        b"trailer\n"
        b"<< /Size " + str(len(objects) + 1).encode() + b" /Root 1 0 R >>\n"
        b"startxref\n" + str(xref_offset).encode() + b"\n"
        b"%%EOF\n"
    )
    return header + body + xref_block + trailer


@pytest.fixture
def sample_pdf(fixtures_dir: Path) -> Path:
    """A 2-page PDF generated by hand.

    Page 1: ``Page One: thermostat setup.``
    Page 2: ``Page Two: advanced settings and troubleshooting.``
    """
    p = fixtures_dir / "manual.pdf"
    p.write_bytes(
        _build_minimal_pdf(
            [
                "Page One: thermostat setup.",
                "Page Two: advanced settings and troubleshooting.",
            ]
        )
    )
    return p


@pytest.fixture
def empty_pdf(fixtures_dir: Path) -> Path:
    """A PDF with one page that has no text — should be EmptyDocumentError."""
    p = fixtures_dir / "empty.pdf"
    p.write_bytes(_build_minimal_pdf([""]))
    return p


@pytest.fixture
def malformed_pdf(fixtures_dir: Path) -> Path:
    """Bytes that are not a valid PDF — should be PdfReadError."""
    p = fixtures_dir / "broken.pdf"
    p.write_bytes(b"this is not a pdf, just plain text bytes")
    return p


# ----------------------------------------------------------------------------
# Tests
# ----------------------------------------------------------------------------


class TestPublicSurface:
    """The expected symbols are exported and importable."""

    def test_subpackage_exports_parse(self) -> None:
        from tinyrag.ingestion import parse as fn

        assert fn is parse

    def test_subpackage_exports_parsed_document(self) -> None:
        from tinyrag.ingestion import ParsedDocument as cls

        assert cls is ParsedDocument

    def test_subpackage_exports_document_parser_protocol(self) -> None:
        from tinyrag.ingestion import DocumentParser as cls

        assert cls is DocumentParser

    def test_subpackage_exports_pdf_parser(self) -> None:
        from tinyrag.ingestion import PdfParser as cls

        assert cls is PdfParser

    def test_subpackage_exports_txt_parser(self) -> None:
        from tinyrag.ingestion import TxtParser as cls

        assert cls is TxtParser

    def test_subpackage_exports_markdown_parser(self) -> None:
        from tinyrag.ingestion import MarkdownParser as cls

        assert cls is MarkdownParser

    def test_subpackage_exports_parser_error(self) -> None:
        from tinyrag.ingestion import ParserError as cls

        assert cls is ParserError

    def test_subpackage_exports_unsupported_format_error(self) -> None:
        from tinyrag.ingestion import UnsupportedFormatError as cls

        assert cls is UnsupportedFormatError

    def test_subpackage_exports_empty_document_error(self) -> None:
        from tinyrag.ingestion import EmptyDocumentError as cls

        assert cls is EmptyDocumentError

    def test_subpackage_exports_pdf_read_error(self) -> None:
        from tinyrag.ingestion import PdfReadError as cls

        assert cls is PdfReadError


class TestProtocolIsRuntime:
    """``DocumentParser`` is duck-typeable via ``@runtime_checkable``."""

    def test_pdf_parser_is_a_document_parser(self) -> None:
        assert isinstance(PdfParser(), DocumentParser)

    def test_txt_parser_is_a_document_parser(self) -> None:
        assert isinstance(TxtParser(), DocumentParser)

    def test_markdown_parser_is_a_document_parser(self) -> None:
        assert isinstance(MarkdownParser(), DocumentParser)

    def test_non_parser_is_not_a_document_parser(self) -> None:
        """A random object lacking ``parse`` should fail isinstance()."""

        class NotAParser:
            pass

        assert not isinstance(NotAParser(), DocumentParser)


class TestParsedDocument:
    """The result dataclass behaves correctly."""

    def test_dataclass_is_frozen(self) -> None:
        doc = ParsedDocument(text="hello")
        with pytest.raises((AttributeError, Exception)):
            doc.text = "world"  # type: ignore[misc]

    def test_pages_default_is_empty(self) -> None:
        """Critical: defaults must NOT be mutable shared state."""
        d1 = ParsedDocument(text="a")
        d2 = ParsedDocument(text="b")
        assert d1.pages == []
        assert d2.pages == []
        d1.pages.append((1, "x"))  # should not affect d2
        assert d2.pages == []

    def test_metadata_default_is_empty(self) -> None:
        d1 = ParsedDocument(text="a")
        d2 = ParsedDocument(text="b")
        d1.metadata["k"] = "v"
        assert "k" not in d2.metadata


class TestExtensionDispatch:
    """:func:`parse` routes to the right parser by file extension."""

    def test_pdf_routes_to_pdf_parser(
        self, sample_pdf: Path
    ) -> None:
        doc = parse(sample_pdf)
        assert doc.metadata["format"] == "pdf"

    def test_txt_routes_to_txt_parser(
        self, sample_txt: Path
    ) -> None:
        doc = parse(sample_txt)
        assert doc.metadata["format"] == "txt"

    def test_md_routes_to_markdown_parser(
        self, sample_md: Path
    ) -> None:
        doc = parse(sample_md)
        assert doc.metadata["format"] == "md"

    def test_markdown_extension_also_works(
        self, sample_md: Path
    ) -> None:
        p = sample_md.with_suffix(".markdown")
        sample_md.rename(p)
        doc = parse(p)
        assert doc.metadata["format"] == "md"

    def test_uppercase_extension_is_case_insensitive(
        self, sample_txt: Path
    ) -> None:
        upper = sample_txt.with_suffix(".TXT")
        sample_txt.rename(upper)
        doc = parse(upper)
        assert doc.metadata["format"] == "txt"

    def test_string_path_is_accepted(self, sample_txt: Path) -> None:
        doc = parse(str(sample_txt))
        assert doc.metadata["format"] == "txt"

    def test_unknown_extension_raises(self, fixtures_dir: Path) -> None:
        p = fixtures_dir / "manual.docx"
        p.write_text("anything", encoding="utf-8")
        with pytest.raises(UnsupportedFormatError):
            parse(p)

    def test_no_extension_raises(self, fixtures_dir: Path) -> None:
        p = fixtures_dir / "noext"
        p.write_text("anything", encoding="utf-8")
        with pytest.raises(UnsupportedFormatError):
            parse(p)

    def test_unknown_extension_error_lists_supported(
        self, fixtures_dir: Path
    ) -> None:
        p = fixtures_dir / "x.docx"
        p.write_text("x", encoding="utf-8")
        with pytest.raises(UnsupportedFormatError) as excinfo:
            parse(p)
        msg = str(excinfo.value)
        # Should mention at least one of the supported extensions so
        # the user knows what's accepted.
        assert ".pdf" in msg or ".txt" in msg or ".md" in msg

    def test_unknown_extension_error_preserves_path(
        self, fixtures_dir: Path
    ) -> None:
        p = fixtures_dir / "x.docx"
        p.write_text("x", encoding="utf-8")
        with pytest.raises(UnsupportedFormatError) as excinfo:
            parse(p)
        assert excinfo.value.path == p


class TestTxtParser:
    """``TxtParser`` happy path + failure modes."""

    def test_happy_path_returns_text_and_metadata(
        self, sample_txt: Path
    ) -> None:
        doc = TxtParser().parse(sample_txt)
        assert "Living-Room Thermostat Manual" in doc.text
        assert doc.metadata["format"] == "txt"
        assert doc.metadata["source"] == "manual.txt"
        assert doc.metadata["page_count"] == 1
        assert doc.metadata["char_count"] == len(doc.text)

    def test_pages_is_single_element(self, sample_txt: Path) -> None:
        doc = TxtParser().parse(sample_txt)
        assert len(doc.pages) == 1
        assert doc.pages[0][0] == 1
        assert doc.pages[0][1] == doc.text

    def test_missing_file_raises_parser_error(
        self, fixtures_dir: Path
    ) -> None:
        with pytest.raises(ParserError):
            TxtParser().parse(fixtures_dir / "does_not_exist.txt")

    def test_empty_file_raises_empty_document_error(
        self, empty_txt: Path
    ) -> None:
        with pytest.raises(EmptyDocumentError):
            TxtParser().parse(empty_txt)

    def test_whitespace_only_file_raises_empty_document_error(
        self, whitespace_txt: Path
    ) -> None:
        with pytest.raises(EmptyDocumentError):
            TxtParser().parse(whitespace_txt)

    def test_bom_is_stripped(self, sample_txt_bom: Path) -> None:
        """UTF-8 BOM (\ufeff) at the start of a Windows-saved file is removed."""
        doc = TxtParser().parse(sample_txt_bom)
        # The BOM should not appear in the extracted text.
        assert "\ufeff" not in doc.text
        assert doc.text.startswith("Hello from Windows Notepad")

    def test_invalid_utf8_raises_unicode_decode_error(
        self, fixtures_dir: Path
    ) -> None:
        p = fixtures_dir / "latin1.txt"
        # 0xff is not a valid UTF-8 start byte; 0xa9 alone (in this
        # position) is also invalid. Together they are a valid
        # Windows-1252 copyright symbol but not valid UTF-8.
        p.write_bytes(b"\xff\xfehello\n")
        with pytest.raises(UnicodeDecodeError):
            TxtParser().parse(p)


class TestMarkdownParser:
    """``MarkdownParser`` happy path + front-matter + link stripping."""

    def test_happy_path_returns_body(
        self, sample_md: Path
    ) -> None:
        doc = MarkdownParser().parse(sample_md)
        assert "## Pairing the bulb" in doc.text
        assert "## Resetting" in doc.text
        assert doc.metadata["format"] == "md"
        assert doc.metadata["source"] == "faq.md"

    def test_frontmatter_is_stripped(self, sample_md: Path) -> None:
        doc = MarkdownParser().parse(sample_md)
        assert "title: Home FAQ" not in doc.text
        assert "author: TinyRAG" not in doc.text
        # Heading should still be there (after the front-matter).
        assert "# FAQ" in doc.text

    def test_had_frontmatter_flag_is_true_when_present(
        self, sample_md: Path
    ) -> None:
        doc = MarkdownParser().parse(sample_md)
        assert doc.metadata["had_frontmatter"] is True

    def test_had_frontmatter_flag_is_false_when_absent(
        self, md_no_frontmatter: Path
    ) -> None:
        doc = MarkdownParser().parse(md_no_frontmatter)
        assert doc.metadata["had_frontmatter"] is False

    def test_link_urls_are_stripped(self, sample_md: Path) -> None:
        doc = MarkdownParser().parse(sample_md)
        assert "https://example.com/guide" not in doc.text
        assert "official guide" in doc.text

    def test_image_urls_and_brackets_are_stripped(
        self, sample_md: Path
    ) -> None:
        doc = MarkdownParser().parse(sample_md)
        assert "https://example.com/diagram.png" not in doc.text
        assert "![" not in doc.text
        assert "wiring diagram" in doc.text

    def test_missing_file_raises_parser_error(
        self, fixtures_dir: Path
    ) -> None:
        with pytest.raises(ParserError):
            MarkdownParser().parse(fixtures_dir / "nope.md")

    def test_empty_file_raises_empty_document_error(
        self, fixtures_dir: Path
    ) -> None:
        p = fixtures_dir / "empty.md"
        p.write_text("", encoding="utf-8")
        with pytest.raises(EmptyDocumentError):
            MarkdownParser().parse(p)

    def test_frontmatter_only_file_is_empty(
        self, md_only_frontmatter: Path
    ) -> None:
        """A file containing only a YAML block has no body — must raise."""
        with pytest.raises(EmptyDocumentError):
            MarkdownParser().parse(md_only_frontmatter)


class TestPdfParser:
    """``PdfParser`` happy path + failure modes."""

    def test_happy_path_returns_text_and_pages(
        self, sample_pdf: Path
    ) -> None:
        doc = PdfParser().parse(sample_pdf)
        assert "Page One" in doc.text
        assert "Page Two" in doc.text
        assert doc.metadata["format"] == "pdf"
        assert doc.metadata["page_count"] == 2
        assert doc.metadata["source"] == "manual.pdf"

    def test_pages_preserves_per_page_text_and_numbers(
        self, sample_pdf: Path
    ) -> None:
        doc = PdfParser().parse(sample_pdf)
        assert len(doc.pages) == 2
        # Pages should be 1-indexed (humans think in 1-based pages).
        assert doc.pages[0][0] == 1
        assert doc.pages[1][0] == 2
        assert "Page One" in doc.pages[0][1]
        assert "Page Two" in doc.pages[1][1]

    def test_missing_file_raises_parser_error(
        self, fixtures_dir: Path
    ) -> None:
        with pytest.raises(ParserError):
            PdfParser().parse(fixtures_dir / "missing.pdf")

    def test_empty_pdf_raises_empty_document_error(
        self, empty_pdf: Path
    ) -> None:
        """A PDF with no extractable text should be flagged empty."""
        with pytest.raises(EmptyDocumentError):
            PdfParser().parse(empty_pdf)

    def test_malformed_pdf_raises_pdf_read_error(
        self, malformed_pdf: Path
    ) -> None:
        """Random bytes (not a real PDF) should be a PdfReadError, not an OS crash."""
        with pytest.raises(PdfReadError):
            PdfParser().parse(malformed_pdf)

    def test_pdf_metadata_char_count_matches_text(
        self, sample_pdf: Path
    ) -> None:
        doc = PdfParser().parse(sample_pdf)
        assert doc.metadata["char_count"] == len(doc.text)


class TestErrorHierarchy:
    """Every public exception inherits from :class:`ParserError`."""

    @pytest.mark.parametrize(
        "exc_cls",
        [
            UnsupportedFormatError,
            EmptyDocumentError,
            PdfReadError,
        ],
    )
    def test_subclass_of_parser_error(
        self, exc_cls: type[ParserError]
    ) -> None:
        assert issubclass(exc_cls, ParserError)

    def test_can_catch_all_with_parser_error(
        self, sample_pdf: Path
    ) -> None:
        """A single ``except ParserError`` catches every parser failure."""
        # We don't actually invoke parse here — we just demonstrate
        # the hierarchy by raising each subclass and catching via base.
        for exc_cls in (
            UnsupportedFormatError,
            EmptyDocumentError,
            PdfReadError,
        ):
            with pytest.raises(ParserError):
                raise exc_cls("test")


class TestJsonSafety:
    """``ParsedDocument.metadata`` is JSON-serialisable for the API.

    The chunker (Step 4.5) will merge each parsed document's metadata
    into the chunk metadata that ends up in SQLite. SQLite stores
    JSON, so this is a precondition for the whole ingestion chain.
    """

    def test_txt_metadata_is_json_serialisable(
        self, sample_txt: Path
    ) -> None:
        doc = parse(sample_txt)
        json.dumps(doc.metadata)  # would raise if not JSON-safe

    def test_md_metadata_is_json_serialisable(
        self, sample_md: Path
    ) -> None:
        doc = parse(sample_md)
        json.dumps(doc.metadata)

    def test_pdf_metadata_is_json_serialisable(
        self, sample_pdf: Path
    ) -> None:
        doc = parse(sample_pdf)
        json.dumps(doc.metadata)
